export let tagList =  [
    "Array",
    "String",
    "Hash Table",
    "Dynamic Programming",
    "Math",
    "Sorting",
    "Greedy",
    "Depth-First Search",
    "Binary Search",
    "Database",
    "Breadth-First Search",
    "Tree",
    "Matrix",
    "Two Pointers",
    "Bit Manipulation",
    "Binary Tree",
    "Heap (Priority Queue)",
    "Stack",
    "Prefix Sum",
    "Graph",
    "Simulation",
    "Design",
    "Counting",
    "Sliding Window",
    "Backtracking",
    "Union Find",
    "Linked List",
    "Enumeration",
    "Ordered Set",
    "Monotonic Stack",
    "Number Theory",
    "Trie",
    "Recursion",
    "Divide and Conquer",
    "Bitmask",
    "Queue",
    "Binary Search Tree",
    "Segment Tree",
    "Memoization",
    "Binary Indexed Tree",
    "Geometry",
    "Topological Sort",
    "Combinatorics",
    "Hash Function",
    "Shortest Path",
    "Game Theory",
    "String Matching",
    "Data Stream",
    "Interactive",
    "Rolling Hash",
    "Brainteaser",
    "Monotonic Queue",
    "Randomized",
    "Merge Sort",
    "Iterator",
    "Concurrency",
    "Doubly-Linked List",
    "Probability and Statistics",
    "Quickselect",
    "Bucket Sort",
    "Suffix Array",
    "Minimum Spanning Tree",
    "Counting Sort",
    "Shell",
    "Line Sweep",
    "Reservoir Sampling",
    "Strongly Connected Component",
    "Eulerian Circuit",
    "Radix Sort",
    "Rejection Sampling",
    "Biconnected Component"
]